FROM alpine:3.7
ENV PFNET_DIR=/pfnet-miner

RUN apk add --update cmake build-base openssl-dev git dos2unix libcurl curl-dev bash
RUN git clone --depth 1 https://github.com/pfnet-software/pfnet-miner ${PFNET_DIR}

RUN cd ${PFNET_DIR} && cmake . && make install

RUN chmod +x ${PFNET_DIR}/pfnet_miner
ENV CONF_NODE http://computation-01.pfnet.org:17876
ENV CONF_NB_THREADS 1
ENV CONF_WALLET_PASSPHRASE 'this is a passphrase'
ENV CONF_API_PASS ''

WORKDIR ${PFNET_DIR}
CMD ./pfnet_miner -t ${CONF_NB_THREADS} -P '${CONF_WALLET_PASSPHRASE}' -D -o ${CONF_NODE} ${CONF_API_PASS}
